### ISSUE TITLE
Different set of augmentations for paper?

### ISSUE THREAD

**Issue by markaustinbrophy** [Britefury/self-ensemble-visual-domain-adapt-photo#1]
Hello, first, thanks for releasing your code. Second, the code as provided consistently gets 84% accuracy on the VisDA validation set (running `run_visda17_trainval_resnet152.sh`), but the number you reached for the paper is 92.6% accuracy. Is there a larger set of augmentations that should be used?

**Comment by Britefury** [comment]
Hi, yes, 84% on the validation set is correct. We get ~92% on the test set.

**Comment by markaustinbrophy** [comment]
Thank you kindly for the quick response.
