### ISSUE TITLE
Reproduce self-ensemble using different base model

### ISSUE THREAD

**Issue by lianqing11** [Britefury/self-ensemble-visual-domain-adapt-photo#2]
Hello, have you try to reproduce the network using different base models such as (resnet50, resnet101 or inception v4) ? I change the resnet152 to resnet101 using the same hyper-parameters, but the performance drops a lot. 

I noticed that you also use ensemble method on the final test phase, I am wonder if you can share some tips to help me.

Best Regards,
Qing Lian

**Comment by Britefury** [comment]
Yes, I noticed that ResNet-101 did not give as good performance as ResNet-50 or ResNet-152.

The ensembling made very little difference. It should do test-time augmentation already, and that will make the biggest difference over vanilla prediction.

**Comment by lianqing11** [comment]
Okay, let me try it. 

Thanks for your respond, and also thanks for releasing your work.

**Comment by Wang-Xiaodong1899** [comment]
Hello! guys! I also noticed that Resnet-101 backbone can not reproduce the good performance. But I am confused that what is your suggestion for the sentence "It should do test-time augmentation already". Can you share me some tips to help me reproduce the better performace using Resnet-101 ?

Best Wishes!
Xiaodong Wang

**Comment by Britefury** [comment]
Hmmm.
About all I can suggest is installing PyTorch v0.4 with the corresponding version of torchvision from that time, as that is the setup that we used.
Beyond that I'm not sure what to advise.

**Comment by Wang-Xiaodong1899** [comment]
Glad to receive the reply so quickly! Thanks a lot! I will try it. Thank you!
