### ISSUE TITLE
difference between "TGT mean class acc" and "TGT AUG mean class acc"

### ISSUE THREAD

**Issue by SmartPorridge** [Britefury/self-ensemble-visual-domain-adapt-photo#4]
Hi,
Thank you for your wonderful work first. I have a question.

What's the difference between "TGT mean class acc" and "TGT AUG mean class acc"? 

Thank you！

**Comment by Britefury** [comment]
"TGT AUG mean class acc" is the mean class accuracy with test time augmentation; e.g. each sample is presented a number of times with different augmentation parameters to the network and the outputs averaged to get the final score. Gets a bit extra score, but not a huge amount.

**Comment by SmartPorridge** [comment]
@Britefury Thanks for your reply. 

Best
